### ISSUE TITLE
Error getting OAuth request token

### ISSUE THREAD

**Issue by shahzad-saddam** [christian-fei/twitter-oauth-login-in-nodejs#3]
I am getting Error getting OAuth request token on staging server but it's working fine on local

**Comment by christian-fei** [comment]
Hello,
could you please provide further information? This way I can't help

**Comment by mikecoon** [comment]
I am also getting this error as well. When I try to click on log in with twitter it fails to open the page and then I get an "Error getting OAuth request token" in console. Not sure why
